### ISSUE TITLE
Suppress the report entirely if there are no flaky tests

### ISSUE THREAD

**Issue by jonparrott** [box/flaky#104]
`--no-success-flaky-report` still outputs an empty flaky report. It'd be nice if it suppressed the output altogether. I'm happy to create a PR for this if you're willing to accept it.

**Comment by Jeff-Meadows** [comment]
Sounds reasonable to me. I'd be happy to review such a PR.

**Comment by jonparrott** [comment]
Great, I'll try to get this submitted tomorrow. :)
