### ISSUE TITLE
Tests are skipped if pytest fixtures fail

### ISSUE THREAD

**Issue by recht** [box/flaky#114]
A test marked with `@flaky` will not be marked as failed if the fixture fails for whatever reason - instead, any error is just swallowed and ignored.

**Comment by Hebbeman** [comment]
Hah, I just logged-in to report exactly this bug. Hope this get fixed.

**Comment by Hebbeman** [comment]
My problem with flaky not reporting tests at all is FIXED with v3.4.0 :)

**Comment by Jeff-Meadows** [comment]
Woot!

**Comment by lalithach** [comment]
Hi, is this issue resolved. I still find this issue with flaky 3.6.1. The problem I am facing is, when there is any exception at the fixture level and the test fails because of it, I don't see flaky rerunning the failed test again. Could someone please help on this. Thanks.
