### ISSUE TITLE
using flaky outside unit tests

### ISSUE THREAD

**Issue by ssbarnea** [box/flaky#118]
I would like to be able to use `@flaky` outside unittests, on normal Python code in order to implement a simple and clean retry mechanism. 

Note: if this is already possible it should be documented.

**Comment by jmoldow** [comment]
Hi @ssbarnea ,

Flaky is only intended for use with unit tests, as a large part of its functionality is to interface with unit test systems (hook into unittest or pytest, re-do setup and teardown, report errors to the system, print the flaky report, etc.)
