### ISSUE TITLE
Feature request: Conditional support in flaky decorator

### ISSUE THREAD

**Issue by dharmab** [box/flaky#137]
We use pytest for integration tests for a multi-cloud codebase. We have a test which is only flaky when it runs within a certain cloud, for reasons beyond our control. It would be nice if we could only enable flaky when running in that cloud with a conditional similar to the `condition` argument to `@pytest.mark.xfail`.

**Comment by Jeff-Meadows** [comment]
I think this is now supported with the addition of `pytest.mark.flaky` and the use of `pytest.mark.parametrize`.

See http://doc.pytest.org/en/latest/example/markers.html#marking-individual-tests-when-using-parametrize

An example,

    @dataclass
    class Wrapper:
        wrapped: int


    @pytest.mark.parametrize(
        ['wrapped_num'],
        (
            (Wrapper(1),),  # passes
            (Wrapper(2),),  # fails
            pytest.param(Wrapper(1), marks=pytest.mark.flaky),  # passes, but uses flaky
            pytest.param(Wrapper(2), marks=pytest.mark.flaky),  # fails, then passes, using flaky
        )
    )
    def test_odd(wrapped_num):
        wrapped_num.wrapped += 1
        assert wrapped_num.wrapped % 2 == 0
