### ISSUE TITLE
Feature request: Export flaky result to file

### ISSUE THREAD

**Issue by tombasche** [box/flaky#149]
We have recently started using Flaky at our organisation to run tests and found it was useful to be able to aggregate and dump the output to a single text file for viewing in Jenkins.

I went ahead and forked it, and made the necessary change already to the pytest plugin, and it's working splendidly for our tests. Basically it's just a new option:

`--export-flaky-report`

which writes to a 'reports' directory (same place as the junit xml files).

Is this something you would like to see in the regular flaky tool? It's got a very specific use case and I'm not sure how useful it is for most unit test suites.

**Comment by simplydv** [comment]
@tombasche please open a PR if you already have a solution :) Thanks!

**Comment by tombasche** [comment]
Unfortunately the repository was with an organisation I am no longer part of, so it's been lost to the ages :(
