### ISSUE TITLE
Is it Possible to do a Flaky Rerun on a Pytest Error rather than a Pytest Failure?

### ISSUE THREAD

**Issue by zesoft23** [box/flaky#186]
Hey folks,

Just wondering if there is a way to use flaky on an error within pytest rather than a failure! I have a couple tests that fail occasionally on setup, but it seems like flaky doesn't pickup an error rather than a failure.

Let me know if you need any particular setup info or if I'm not making sense!

**Comment by bkthomps** [comment]
Since version 3.7.0 it supports flaky test retrying on Error on setup
