### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by karimtabet** [box/flaky#20]
Found an issue when building with Flaky.

flaky/flaky_nose_plugin.py", line 145, in _get_test_method_name
    _, _, class_and_method_name = test.address()
ValueError: too many values to unpack

Looks like a tuple issue.

**Comment by Jeff-Meadows** [comment]
Hey @karimtabet - thanks for reporting this issue, and sorry I missed it until now.

Can you give me an example of a test function/method/class that has this issue?

**Comment by Jeff-Meadows** [comment]
Closing after > 2 months of inactivity.
