### ISSUE TITLE
crash if using Nose short test naming convention

### ISSUE THREAD

**Issue by johntellsall** [box/flaky#22]
If a test uses Nose's "short style" tests, Flaky gets confused about the test name, and crashes.

Test case:

test_nose_example.py
-------------------------------
```
# USAGE:
# 	nosetests -s --with-flaky ./test/test_nose_example.py

from nose.tools import eq_

def test1():
    eq_(1, 1)
```

**Comment by potrebic** [comment]
Thanks John! See the comment I posted in the commit on your fork.
