### ISSUE TITLE
Flaky report missing in stdout w/ nosetests

### ISSUE THREAD

**Issue by 0x1mason** [box/flaky#29]
I only ever see the flaky report when my tests short circuit and (presumably) stderr prints to console.  However, if my tests run completely, there's no flaky report at the end. I'm running nosetests 1.3.4 and flaky 2.0.0.

Here's a sample command line:

`nosetests -a '!quarantine'  -v -s --with-flaky --processes=4 --process-timeout=12000 mytests.py`

I'm certain that flaky is loaded and it shows up in `nosetests --plugins`.

**Comment by Jeff-Meadows** [comment]
Hi, thanks for the report. I'm having trouble replicating the issue. If I run:

    nosetests --with-flaky -v -s test/test_example.py:ExampleTests.test_non_flaky_thing

(which is only one test, not marked flaky, definitely doesn't short circuit), I still see the flaky test report.

    $ nosetests --with-flaky test/test_example.py:ExampleTests.test_non_flaky_thing -s -v
    Flaky will not interact with this test ... ok
    
    ===Flaky Test Report===
    
    
    ===End Flaky Test Report===

**Comment by 0x1mason** [comment]
We ended up not using flaky in our project, so I no longer need support for this issue :(  Thanks for getting back to me!
