### ISSUE TITLE
Test classes inheriting TestCase aren't rerun with pytest?

### ISSUE THREAD

**Issue by simlun** [box/flaky#30]
Hi! This seems like a really useful tool! But I'm having some troubles getting it to work with my project.

In the readme there's an example of "Marking a class flaky":

```
@flaky
class TestMultipliers(TestCase):
    def test_flaky_doubler(self):
        value_to_double = 21
        result = get_result_from_flaky_doubler(value_to_double)
        self.assertEqual(result, value_to_double * 2, 'Result doubled incorrectly.')
```

Note how it's inheriting `TestCase`. That's how we are writing our test classes in the project I tried to use `flaky` in.

The problem is that it does not seem to retry the tests if classes are inheriting `TestCase` when using pytest. It only works if it's inheriting `object`, like in the `test_pytest_example.py` module.

Please see my fork for an example of a test case that fails but shouldn't (?)
- Commit: https://github.com/simlun/flaky/commit/6c0c7fcc11de73c00f5430f404b816ecfef9a099
- Failing CI log: https://travis-ci.org/simlun/flaky/jobs/53627102

Best regards
Simon

**Comment by Jeff-Meadows** [comment]
Thanks for trying out flaky! This seems like a bug. I'll check it out.

**Comment by simlun** [comment]
Oh, fantastic! Can't wait to try it out :)

**Comment by Jeff-Meadows** [comment]
Make sure to update to flaky 2.0.3, which I just pushed to pypi.
