### ISSUE TITLE
flaky passes tests even if it fails on every try

### ISSUE THREAD

**Issue by lbrindze** [box/flaky#32]
When I run flaky with selenium, it appears that flaky suppresses errors and possibly failures as well.

the below code shows you how the flaky decorator is applied (though the complete integration test is a bit of a bother so I gave the abridged version).

``` python
@flaky(max_runs=3, min_passes=1)
class TestLoginModalInteractions(ModalTestCases):

    def test_ajax_modal_launch(self):
        # open modal from login link
        self.open_modal_link()

        # check everything is there
        self.assertIdExists('login_form')
        self.assertClassExists('mfp-bg')

        # check everything closes correct
        self.driver.find_element_by_class_name('mfp-bg').click()
        mfp_modal_blur = self.driver.find_elements_by_class_name('mfp-bg')
        self.assertTrue(len(mfp_modal_blur) == 0)
```

This is my output when I run the test with the flaky decorator:
![screen shot 2015-04-04 at 10 22 33 am](https://cloud.githubusercontent.com/assets/3255779/6993804/8e014794-dab5-11e4-81e0-6e224f1cac7a.png)

and here is the output when I run it without the flaky decorator:
![screen shot 2015-04-04 at 10 28 11 am](https://cloud.githubusercontent.com/assets/3255779/6993806/99dbba36-dab5-11e4-9766-71ec8b0a9533.png)

I've read over your docs, I think this is a bug, but correct me if I am wrong.

**Comment by Jeff-Meadows** [comment]
Looks like a bug to me.

What's the class hierarchy of `ModalTestCases`?

**Comment by lbrindze** [comment]
django.test.testcases.LiveServerTestCase,
 django.test.testcases.TestCase,
 django.test.testcases.TransactionTestCase,
 django.test.testcases.SimpleTestCase,
 unittest.case.TestCase,
 object,

(and these are our custom test cases that add a few special methods for different cases.  These Classes are all derived from the above)
 tests.test_integrations.TestHelpers
 tests.test_views.ClientEnabledTest,
 tests.test_integrations.ModalTestCases,
 tests.test_integrations.IntegrationTest,

I wonder if there is some conflict on our source code end?  Thank you so much for the quick reply and help.  Please let me know if there is anything else I can provide to help.

**Comment by lbrindze** [comment]
err, I'm gonna put my foot in my mouth on this one, I was using a way deprecated version. Hopefully I didn't waste anyones time, good to know you guys are active on this though!
