### ISSUE TITLE
does it work with pytest-xdist?

### ISSUE THREAD

**Issue by kmike** [box/flaky#35]
I'm running tests in parallel using pytest-xdist. There were test failures in tests decorated with `@flaky`, and flaky printed an empty report:

```
===Flaky Test Report===


===End Flaky Test Report===
```

I'm not sure, but it seems flaky didn't try to re-run failed tests. There were no flaky-related messages in the log.

**Comment by Jeff-Meadows** [comment]
I've never tested flaky with pytest-xdist, although I'd like it to work.

I'll check it out later this week.

**Comment by kmike** [comment]
Thanks Jeff!

**Comment by dhillman-handy** [comment]
:+1: for this. Flaky is particularly useful for automated testing, since automated tests can sometimes fail for reasons that don't have to do with the test itself. However, parallelization is very important as well, since those types of tests tend to be slow. Hope this is ready soon!

**Comment by Jeff-Meadows** [comment]
Hey all - I don't have a ton of experience with pytest-xdist, but I did some digging and at least seem to have gotten the flaky report to print when using xdist and the tests do seem to be getting rerun.

Would you mind pulling down my PR and making sure it solves your problems? If it does, I'll be happy to spruce it up, write some tests, push the PR, and bump the version so everyone can start using it.

If not, well, we'll keep cracking at it.

**Comment by dhillman-handy** [comment]
Hi Jeff, thanks a lot for this. We really appreciate how quickly you started to address this issue. I have just run it with our entire test suite, which included a test that would purposely fail on the first attempt and pass on the second. When doing this, the following stacktrace appeared (note: in the command I issued to run the tests, I had to remove the url for our development environment since this is a public forum):

![screen shot 2015-04-17 at 11 10 58 am](https://cloud.githubusercontent.com/assets/10351789/7204894/94bb8a8e-e4f3-11e4-9f2a-fb027d0d2e04.png)

**Comment by Jeff-Meadows** [comment]
Thanks for the feedback. I see two problems at this moment - first, my PR doesn't always initialize the flaky report in the slaveoutput (which can be easily fixed), but second, the --boxed option to xdist currently interrupts other plugins by hooking into `pytest_runtest_protocol` and returning `True`, meaning no further hooks will be called.

So far, I haven't figured out an effective way to get around that. Ideas are welcome!

**Comment by kmike** [comment]
Hi @Jeff-Meadows,

Thanks for looking at it! It'd be very helpful to support pytest-xdist even without --boxed option. I personally have only ever used pytest-xdist parallelization features.

**Comment by ericmedvec** [comment]
+1 on the previous comment. If --boxed is too tricky to implement, I'd personally love to have it working in xdist without it.

**Comment by Jeff-Meadows** [comment]
@kmike @ericmedvec Would you mind testing out code from my latest PR #38 to ensure it works for your test cases? If so, I'll push the PR along with some documentation that states flaky is compatible with pytest-xdist but not when using the --boxed option.

**Comment by kmike** [comment]
@Jeff-Meadows #38 works for me :+1:  I've also tried it together with #37 and was able to run a full testing suite.

**Comment by ericmedvec** [comment]
@Jeff-Meadows  :+1: Works well for me too!

**Comment by Jeff-Meadows** [comment]
Great - please upgrade to flaky 2.0.4, and you should be good to go!
