### ISSUE TITLE
tearDown() not called between reruns

### ISSUE THREAD

**Issue by Yaro70** [box/flaky#39]
Hi,

Thanks for what seems to be a very promising idea...
I tried to use flaky with nosetests, however I find that the tests are rerun for fails fine but the tearDown() does not get called between reruns until the very end when all reruns are finished, which is not good the test can leave something behind on the environment. Is this how flaky was designed or is it an actual issue?

Thanks,
Regards,
Yaro

**Comment by Jeff-Meadows** [comment]
Hi Yaro - good question.

Unfortunately, nosetests plugins can only use a certain number of entry points, and the one to handle a test failure or error is called before test `tearDown()`.

However, I think it's possible to modify flaky to run tearDown after each test, pass or fail. I'll see what I can come up with.

**Comment by Yaro70** [comment]
Thanks Jeff, much appreciated.
So you are saying that this happens due to the nature of nosetests not calling tearDown() until the test is marked as passed or failed (which of course is not done between test re-runs by flaky), but its possible to overcome this through modification to flaky or perhaps I misunderstood your comment?

Regards,
Yaro
