### ISSUE TITLE
nose --with-flaky causes non-annotated test error reports to appear twice

### ISSUE THREAD

**Issue by cbetti** [box/flaky#45]
When running nosetests --with-flaky, an error in a test function that is not annotated with @flaky will show 'EE' in the summary, and will have its error report duplicated.

I've confirmed that the test function is not being run twice, this seems like a reporting problem only.

    $ pip3 freeze
    flaky==2.1.1
    nose==1.3.7

**Comment by Jeff-Meadows** [comment]
Thanks for the report - I'll look into it!
