### ISSUE TITLE
pytest: test re-run should also include resetup of all the test-scoped fixtures

### ISSUE THREAD

**Issue by bubenkoff** [box/flaky#53]
This is obviously required if fixtures are mutable
For example: test logs in using a 'browser' fixture and checks some content on the page loaded by ajax
It can be flaky if there's some timeout for ajax to load
But with this plugin it will not work as test will not be able to log in again as it's already logged in

**Comment by bubenkoff** [comment]
This is what i would see this plugin does:

```python
def call_and_report(plugin, last, terminalreporter, item, when, log=True, **kwds):
    """Skip falure reporting if test run is not last."""
    call = plugin.call_runtest_hook(item, when, **kwds)
    if not last:
        if call.excinfo:
            call.excinfo = None
            terminalreporter.write_line('Retrying potentially flaky test...')
    hook = item.ihook
    report = hook.pytest_runtest_makereport(item=item, call=call)
    if log:
        hook.pytest_runtest_logreport(report=report)
    if plugin.check_interactive_exception(call, report):
        hook.pytest_exception_interact(node=item, call=call, report=report)
    return report


def pytest_runtest_protocol(item, nextitem):
    """Rerun flaky tests."""
    runner = item.config.pluginmanager.getplugin("runner")
    old_call_and_report = runner.call_and_report
    terminalreporter = item.config.pluginmanager.getplugin('terminalreporter')
    try:
        def run():
            runner.pytest_runtest_protocol(item, nextitem)

        for index in xrange(3):
            runner.call_and_report = partial(call_and_report, runner, index == 2, terminalreporter)
            run()
            break
    finally:
        runner.call_and_report = old_call_and_report
```
this works as expected with setup/teardown of the fixtures

**Comment by Jeff-Meadows** [comment]
Thanks for the report. I think you're right, that it should recreate fixtures. I'll work on a fix.

**Comment by Jeff-Meadows** [comment]
Hi - I haven't forgotten about this, but I haven't made a ton of progress yet. I'll keep this issue updated when I do.

**Comment by bubenkoff** [comment]
i tried as well, without changes to the core of pytest it's not possible,
im affraid
and changes are not at all cosmetic

**Comment by paurullan** [comment]
I patched the `flaky_pytest_plugin.py` with the code above and it seems to work. Altought flaky's own tests fail afterwards, so I will have to check what is going on.

Have you made any advance in this issue?

**Comment by Jeff-Meadows** [comment]
@bubenkoff @mangeld Please check PR #76 to see if it fixes the issues you're having with flaky.
