### ISSUE TITLE
Add an ability to specify non-retried exceptions

### ISSUE THREAD

**Issue by DanaGoyette** [box/flaky#54]
I'd like to use the "flaky" module, but before it's useful for my use case, I'll need to be able to specify which exception classes to retry, either as a whitelist or as a blacklist.

As an example, I'd like to make sure exceptions in my "product crashed" class hierarchy are reported immediately.

**Comment by Jeff-Meadows** [comment]
Hi Dana, Please check out flaky 2.2.0 and see if the rerun_filter works for you.

My idea is that you can specify a rerun filter that is flexible enough for your whitelist or blacklist.

**Comment by DanaGoyette** [comment]
Cool, that rerun filter looks like a great way of doing things.  Thanks.

Is there any way to specify a given function as the default rerun filter, so tests can just mark "flaky", and so --force-flaky will apply the filter?

With the code as-is, I can replace flaky.defaults._true() function with the desired filter, but it would be nicer to have an official way of doing it.

**Comment by Jeff-Meadows** [comment]
I didn't add a way to specify a default. That'd be a nice addition.

I was thinking you'd do something like this:

*    def **flaky_filter*(err, name, test, plugin):        *return
*False*    def **filtered_flaky*(*args, **kwargs):        *return
*flaky(*args, rerun_filter=flaky_filter, **kwargs)
@filtered_flaky(5, 1)*    def **test_something_with_no_rerun*():
 *assert *False

**Comment by Jeff-Meadows** [comment]
I didn't add a way to specify a default. That'd be a nice addition.

I was thinking you'd do something like this:

    def flaky_filter(err, name, test, plugin):
        return False

    def filtered_flaky(*args, **kwargs):
        return flaky(*args, rerun_filter=flaky_filter, **kwargs)

    @filtered_flaky(5, 1)
    def test_something_with_no_rerun():
        assert *False

**Comment by Jeff-Meadows** [comment]
Should be resolved in flaky 2.2.0. If not, feel free to reopen.
