### ISSUE TITLE
Delay

### ISSUE THREAD

**Issue by wernight** [box/flaky#73]
It would be useful to have a `delay` optional parameter that would add a sleep between each retry.

Also a `msg` or `message` would be useful just as a way to have also in the output why it may be flaky (in cases it flakes or fails especially).

**Comment by Jeff-Meadows** [comment]
Flaky can be configured to call a function after a flaky failure. It was designed as a way to skip reruns, but it could also be used to delay them. See #55 for more details. I'd imagine you'd do something like this:

    import time

    def delay_rerun(*args):
        time.sleep(1)
        return True

    @flaky(rerun_filter=delay_rerun)
    def test_flaky_thing():
        pass

**Comment by Jeff-Meadows** [comment]
Sorry, I didn't address your second point. I'm not sure what kind of message you mean. The flaky report includes info about flaky tests failing.
