### ISSUE TITLE
Using flaky breaks test reporting

### ISSUE THREAD

**Issue by sajnikanth** [box/flaky#88]
**Info**
Report generation breaks when using `flaky` with [Allure](http://allure.qatools.ru) or [nosedbreport](https://github.com/alisaifee/nosedbreport).

**Steps (allure)**

* Setup `allure`
* Setup `flaky`
* This is my test: `test.py`
```
from flaky import flaky

@flaky
def test_1():
     assert 1 == 1, 'error message'
```
* Run this test with `allure` without `flaky`
```
nosetests test.py --with-allure --logdir=./allure-results
```
* Check result generated
```
	<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1452172898710" stop="1452172898711">
	  <name>test</name>
	  <test-cases>
	    <test-case start="1452172898710" status="passed" stop="1452172898710">
	      <name>test.test_1</name>
	      <attachments/>
	      <labels/>
	      <steps/>
	    </test-case>
	  </test-cases>
	  <labels/>
	</ns0:test-suite>
```
* Run this test again with `allure` and `flaky`
```
nosetests test.py --with-allure --logdir=./allure-results-flaky --with-flaky
```
* Check result generated
```
	<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1452172868032" stop="1452172868033">
	  <name>test</name>
	  <test-cases/>
	  <labels/>
	</ns0:test-suite>
```

**Comment by Jeff-Meadows** [comment]
Looks like the nose plugin isn't returning the correct values from some of the hook implementations.

I'll take a look at each one and make sure to follow the spec correctly.

Thanks for the report!

**Comment by sajnikanth** [comment]
Thank you; it works now
