### ISSUE TITLE
pytest , tox , flaky;'TestReport' object has no attribute 'item'

### ISSUE THREAD

**Issue by nvdeepa** [box/flaky#91]
During results reporting I get this error, seems to be a basic issue, any help is appreciated.

....test completed successfully .....

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/main.py", line 121, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 301, in __call__
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 299, in <lambda>
INTERNALERROR>     outcome = _CallOutcome(lambda: self.oldcall(hook, hook_impls, kwargs))
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/main.py", line 146, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 301, in __call__
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 299, in <lambda>
INTERNALERROR>     outcome = _CallOutcome(lambda: self.oldcall(hook, hook_impls, kwargs))
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 253, in _wrapped_call
INTERNALERROR>     return call_outcome.get_result()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/flaky/flaky_pytest_plugin.py", line 84, in pytest_runtest_protocol
INTERNALERROR>     self.runner.pytest_runtest_protocol(item, nextitem)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/runner.py", line 65, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/runner.py", line 75, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/runner.py", line 123, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 301, in __call__
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 299, in <lambda>
INTERNALERROR>     outcome = _CallOutcome(lambda: self.oldcall(hook, hook_impls, kwargs))
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/resultlog.py", line 74, in pytest_runtest_logreport
INTERNALERROR>     res = self.config.hook.pytest_report_teststatus(report=report)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 301, in __call__
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 279, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
INTERNALERROR>     self.result = func()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 299, in <lambda>
INTERNALERROR>     outcome = _CallOutcome(lambda: self.oldcall(hook, hook_impls, kwargs))
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 249, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/tmp/devpi-test3/dlb-dcp-test-1.1.0.dev12/.tox/prod1/lib/python2.7/site-packages/flaky/flaky_pytest_plugin.py", line 150, in pytest_report_teststatus
INTERNALERROR>     item = report.item
INTERNALERROR> AttributeError: 'TestReport' object has no attribute 'item'
(debug) [scutils-plugin]Forcing to serialize the specmap file during scutils session finish
(info) [dvcp-dev-2.2.0.58-junit-cucm-prod1.specmap] saving report to /home-local/voiceqa/jenkins/workspace/voiceqa-dlb-dcp-tests-ProdAutoLab-voiceqaDevIndex/dvcp-dev-2.2.0.58-junit-cucm-prod1.specmap

packages in the tox environment for the above run:

(prod1)[voiceqa@dsv-bvsrv-08 ~]$ pip freeze
You are using pip version 6.1.1, however version 8.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
beautifulsoup4==4.4.1
configparser2==4.0.0
dlb-dcp-ap==1.1.0.dev13
dlb-dcp-prov-client==1.2.0.dev9
dlb-dcp-test==1.1.0.dev12
dlb-voice-common==1.0.0
dolby-commander==2.1.0
flaky==3.0.3
gti-common==1.2.0.dev1
gti-containers==3.0
gti-docutils==1.0
gti-scutils==1.0.6
gti-toolwrappers==2.0.1
gti-utils==2.0.1
html2text==2016.1.8
httplib2==0.9.2
pexpect==4.0.1
ptyprocess==0.5
py==1.4.31
Pyro4==4.39
pytest==2.8.5
pytest-scutils==1.0.1
pytest-specmap==1.0.3
python-dateutil==2.4.2
pytl==1.0.2
PyYAML==3.11
requests==2.9.1
serpent==1.12
six==1.10.0
wget==3.2
xlrd==0.9.4
xlutils==1.7.1
xlwt==1.0.0
(prod1)[voiceqa@dsv-bvsrv-08 ~]$

**Comment by Jeff-Meadows** [comment]
Hi @nvdeepa it's likely that another plugin is conflicting with flaky. Could you run ``py.test --traceconfig --collect-only`` which will print a list of active plugins. Then we might be able to determine if that's the case.
