### ISSUE TITLE
Flaky doesn't work with xdist

### ISSUE THREAD

**Issue by MagiMaster** [box/flaky#92]
Flaky adds the item field to the report in pytest_runtest_makereport, which is of a type that execnet can't serialize in gateway_base.py, which leads to an error like this:
INTERNALERROR>   File "/usr/local/lib/python2.7/dist-packages/execnet/gateway_base.py", line 1388, in _save
INTERNALERROR>     raise DumpError("can't serialize %s" % (tp,))
INTERNALERROR> DumpError: can't serialize <class '_pytest.unittest.TestCaseFunction'>

Versions used: Python 2.7.6, pytest-2.8.3, py-1.4.30, pluggy-0.3.1, flaky-3.0.1, random-0.02, xdist-1.13.1

**Comment by emedvec-handy** [comment]
We are experiencing the same issue.

**Comment by MagiMaster** [comment]
If you work around the DumpError, there's a second issue:

dsession.py, line 282, in remove_item
INTERNALERROR>     self.node2pending[node].remove(item_index)
INTERNALERROR> ValueError: list.remove(x): x not in list

It looks like flaky isn't telling xdist to keep the test in the scheduler, so it's not there the second (etc.) time it tries delete it. This happens whenever there's a failed or skipped test (at least a skipped unittest test).

**Comment by scribu** [comment]
Ran into the same problem. Extra sadness due to the fact that the docs say that it should work:

> Py.test. Works with pytest-xdist but not with the –boxed option. Doctests cannot be marked flaky.

**Comment by Jeff-Meadows** [comment]
Sorry about this - after this issue is resolved, we'll make sure to add a test using xdist to our CI.

I'll work on this ASAP.

**Comment by Jeff-Meadows** [comment]
@MagiMaster do you have an idea of how flaky could tell xdist not to remove a test from the scheduler?

**Comment by MagiMaster** [comment]
Unfortunately not without changing xdist. Somehow it worked before, but I couldn't figure out how.

**Comment by scribu** [comment]
Works now. Thanks guys :cake:

**Comment by murawskikrzysiek** [comment]
Hi,

I just found out that the same issue still occurs for xfail. Now this does not make much sense to use flaky and xfail, but in my case the xfail was just for one platform and specific conditions.
