### ISSUE TITLE
Which test to run when packaging for linux distribution

### ISSUE THREAD

**Issue by DamienCassou** [box/flaky#97]
Hi,

I'm packaging flaky for my linux distribution nixos. Which tests are important to run when checking the package? What are their dependencies?

Thanks

**Comment by Jeff-Meadows** [comment]
Hi,

All the tests can be run using `tox`, and the test commands are specified in `tox.ini` under the `[testenv]` section. Requirements are specified in `requirements-dev.txt`.

Feel free to reopen with additional specific questions.
